"""
常见 OTC 药品说明书静态数据 — 53 条。
每条覆盖: 适应症 / 用法用量 / 禁忌 / 不良反应, 供 RAG 检索用。
注意: 数据为药学常识摘要, 仅供参考, 实际以最新 NMPA 说明书为准。
"""
from __future__ import annotations

DRUGS: list[dict] = [
    {
        "drug_name": "连花清瘟胶囊",
        "category": "中成药 / 感冒",
        "indications": "用于治疗流行性感冒属热毒袭肺证, 症见发热、恶寒、肌肉酸痛、鼻塞流涕、咳嗽、头痛、咽干咽痛、舌偏红、苔黄或黄腻。",
        "dosage": "口服。成人一次 4 粒, 一日 3 次。疗程 7 天。",
        "side_effects": "偶见胃肠道不适、恶心、腹泻、皮疹。",
        "contraindications": "孕妇禁用。对本品过敏者禁用。风寒感冒者不适用。",
        "source": "国家药品说明书 / 中医药管理局《中医药治疗流感临床实践指南》",
    },
    {
        "drug_name": "布洛芬缓释胶囊",
        "category": "解热镇痛 / 退烧",
        "indications": "用于缓解轻至中度疼痛如头痛、关节痛、偏头痛、牙痛、肌肉痛、神经痛、痛经。也用于普通感冒或流行性感冒引起的发热。",
        "dosage": "口服。成人一次 1 粒 (0.3g), 早晚各一次。",
        "side_effects": "少数患者有恶心、呕吐、胃烧灼感、轻度消化不良, 偶见皮疹、转氨酶升高。",
        "contraindications": "对其他非甾体抗炎药过敏者禁用。孕妇及哺乳期妇女禁用。活动性消化道溃疡禁用。",
        "source": "国家药品说明书 / WHO 基本药物清单",
    },
    {
        "drug_name": "布洛芬混悬液 (美林)",
        "category": "儿童退烧",
        "indications": "用于儿童普通感冒或流感引起的发热、头痛。也可用于缓解儿童轻中度疼痛。",
        "dosage": "口服, 用前摇匀。6-12 岁儿童一次 5-10 ml; 1-6 岁一次 3-5 ml。若持续发热, 可间隔 4-6 小时重复用药 1 次, 24 小时不超过 4 次。按体重 5-10 mg/kg。",
        "side_effects": "偶见轻度消化不良、皮疹。",
        "contraindications": "对阿司匹林或其他非甾体抗炎药过敏者禁用。",
        "source": "WHO 儿童退烧用药指南",
    },
    {
        "drug_name": "对乙酰氨基酚片 (必理通)",
        "category": "解热镇痛 / 退烧",
        "indications": "用于普通感冒或流行性感冒引起的发热, 也用于缓解轻中度疼痛如头痛、关节痛、偏头痛、牙痛、肌肉痛、神经痛、痛经。",
        "dosage": "口服。成人一次 0.3-0.6 g, 4-6 小时一次, 24 小时内不超过 2 g。儿童按体重 10-15 mg/kg, 每 4-6 小时一次。",
        "side_effects": "偶见皮疹、粒细胞减少。长期大量使用可致肝肾功能损害。",
        "contraindications": "严重肝肾功能不全者禁用。3 岁以下婴幼儿慎用。",
        "source": "中国药典 2020 版",
    },
    {
        "drug_name": "藿香正气水",
        "category": "中成药 / 暑湿",
        "indications": "用于外感风寒、内伤湿滞或夏伤暑湿所致的感冒, 症见头痛昏重、胸膈痞闷、脘腹胀痛、呕吐泄泻; 胃肠型感冒见上述证候者。",
        "dosage": "口服。一次 5-10 ml, 一日 2 次, 用时摇匀。",
        "side_effects": "偶见恶心、呕吐、皮疹。本品含乙醇, 服用后不得驾驶机/车/船。",
        "contraindications": "孕妇及对乙醇过敏者禁用。不适用于风热感冒。",
        "source": "国家药监局 OTC 说明",
    },
    {
        "drug_name": "藿香正气胶囊",
        "category": "中成药 / 暑湿",
        "indications": "同藿香正气水。适用于不耐受乙醇的驾驶员、儿童、孕妇以外的成人。",
        "dosage": "口服。一次 2-4 粒, 一日 2 次。",
        "side_effects": "偶见胃部不适。",
        "contraindications": "孕妇禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "维生素C泡腾片",
        "category": "维生素 / 营养",
        "indications": "用于防治坏血病, 也用于各种急慢性传染疾病及紫癜等的辅助治疗。",
        "dosage": "用冷水或温开水溶解后服用, 成人一日 1 片 (1g)。",
        "side_effects": "长期大剂量服用 (1g/日) 可致尿酸盐、半胱氨酸盐或草酸盐结石。",
        "contraindications": "半胱氨酸尿症、痛风、高草酸盐尿症、草酸盐沉积症、尿酸盐性肾结石患者禁用。",
        "source": "中国营养学会 DRIs 2023",
    },
    {
        "drug_name": "感冒灵颗粒",
        "category": "感冒 / 复方",
        "indications": "用于感冒引起的头痛、发热、鼻塞、流涕、咽痛。",
        "dosage": "开水冲服。一次 10 g (1 袋), 一日 3 次。",
        "side_effects": "偶见困倦、嗜睡、口渴、虚弱感。",
        "contraindications": "严重肝肾功能不全者禁用。驾驶机/车/船者慎用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "维C银翘片",
        "category": "中成药 / 感冒",
        "indications": "用于外感风热所致的流行性感冒, 症见发热、头痛、咳嗽、口干、咽喉疼痛。",
        "dosage": "口服。一次 2 片, 一日 3 次。",
        "side_effects": "可见困倦、嗜睡、口渴、虚弱感。",
        "contraindications": "肝肾功能不全者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "板蓝根颗粒",
        "category": "中成药 / 清热",
        "indications": "用于肺胃热盛所致的咽喉肿痛、口咽干燥; 急性扁桃体炎见上述证候者。",
        "dosage": "开水冲服。一次 5-10 g (含蔗糖) 或一次 3-6 g (无蔗糖), 一日 3 次。",
        "side_effects": "罕见过敏反应。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "抗病毒口服液",
        "category": "中成药 / 抗病毒",
        "indications": "用于风热感冒, 流感。",
        "dosage": "口服。一次 10 ml, 一日 2-3 次 (饭前空腹服用)。",
        "side_effects": "偶见恶心、呕吐。",
        "contraindications": "孕妇、哺乳期妇女禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "阿莫西林胶囊",
        "category": "抗生素 (需处方)",
        "indications": "用于敏感菌所致的下列感染: 中耳炎、鼻窦炎、咽炎、扁桃体炎等上呼吸道感染; 急性支气管炎、肺炎等下呼吸道感染; 皮肤及软组织感染; 泌尿生殖道感染。",
        "dosage": "口服。成人一次 0.5 g, 每 6-8 小时一次, 一日剂量不超过 4 g。",
        "side_effects": "恶心、呕吐、腹泻、皮疹、过敏性休克。",
        "contraindications": "青霉素过敏及青霉素皮肤试验阳性患者禁用。传染性单核细胞增多症患者禁用。",
        "source": "国家药品说明书 / 需凭医师处方销售",
    },
    {
        "drug_name": "头孢克肟分散片",
        "category": "抗生素 (需处方)",
        "indications": "用于敏感菌所致的咽炎、扁桃体炎、急性支气管炎、慢性支气管炎急性发作、中耳炎、尿路感染、单纯性淋病等。",
        "dosage": "口服。成人一次 0.1 g (1 片), 一日 2 次; 严重感染可增至一次 0.2 g, 一日 2 次。",
        "side_effects": "腹泻、恶心、皮疹、转氨酶升高。",
        "contraindications": "对头孢菌素过敏者禁用。对青霉素有严重过敏史者慎用。",
        "source": "国家药品说明书 / 需凭医师处方销售",
    },
    {
        "drug_name": "奥司他韦胶囊 (达菲)",
        "category": "抗病毒 (需处方)",
        "indications": "用于成人和 1 岁及以上儿童的甲型和乙型流感治疗。在流感症状开始的 48 小时内使用。",
        "dosage": "口服。成人一次 75 mg, 一日 2 次, 共 5 天。1 岁以上儿童按体重调整。",
        "side_effects": "恶心、呕吐、头痛。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书 / 流感诊疗方案 2024",
    },
    {
        "drug_name": "铝碳酸镁片 (达喜)",
        "category": "胃药 / 抗酸",
        "indications": "用于缓解胃酸过多引起的胃灼热 (烧心) 和慢性胃炎。",
        "dosage": "咀嚼服用。一次 1-2 片, 餐后 1-2 小时、睡前或胃部不适时服用。",
        "side_effects": "偶见便秘、稀便、口干和食欲不振。",
        "contraindications": "严重肾功能不全者禁用。低磷血症者禁用。",
        "source": "《中国胃食管反流病诊治指南》",
    },
    {
        "drug_name": "奥美拉唑肠溶胶囊",
        "category": "PPI / 抑酸",
        "indications": "用于胃溃疡、十二指肠溃疡、应激性溃疡、反流性食管炎、卓-艾综合征。",
        "dosage": "口服, 空腹整粒吞服, 不可咀嚼。十二指肠溃疡: 一次 20 mg, 早晨一次。反流性食管炎: 一次 20-40 mg, 早晨一次。",
        "side_effects": "头痛、腹泻、恶心、便秘。长期使用可能影响钙/镁/维生素B12吸收。",
        "contraindications": "对本品过敏者禁用。严重肾功能不全者禁用。",
        "source": "国家药品说明书 / 疗程不超过 8 周",
    },
    {
        "drug_name": "莫沙必利片",
        "category": "促胃肠动力",
        "indications": "用于功能性消化不良伴有胃灼热、嗳气、恶心、呕吐、早饱、上腹胀等消化道症状。",
        "dosage": "口服, 饭前服用。一次 5 mg, 一日 3 次。",
        "side_effects": "偶见腹泻、腹痛、口干、皮疹。",
        "contraindications": "对本品过敏者禁用。胃肠道出血、肠梗阻患者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "氯雷他定片",
        "category": "抗组胺 / 抗过敏",
        "indications": "用于缓解过敏性鼻炎有关的症状, 如喷嚏、流涕、鼻痒、鼻塞以及眼部痒及烧灼感。亦适用于缓解慢性荨麻疹、瘙痒性皮肤病及其他过敏性皮肤病的症状。",
        "dosage": "口服。成人及 12 岁以上儿童一次 10 mg, 一日 1 次。",
        "side_effects": "偶见嗜睡、头痛、口干、疲乏。",
        "contraindications": "对本品过敏者禁用。",
        "source": "《变应性鼻炎诊断和治疗指南》2022",
    },
    {
        "drug_name": "西替利嗪片",
        "category": "抗组胺 / 抗过敏",
        "indications": "用于季节性或常年性过敏性鼻炎, 过敏性结膜炎及过敏引起的瘙痒、荨麻疹。",
        "dosage": "口服。成人一次 10 mg, 一日 1 次, 或早晚各 5 mg。",
        "side_effects": "偶见困倦、头痛、口干。",
        "contraindications": "严重肾功能损害者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "盐酸氨溴索口服液",
        "category": "化痰",
        "indications": "用于伴有痰液分泌异常或排痰功能不良的急、慢性支气管肺疾病。",
        "dosage": "口服, 餐时服用。成人及 12 岁以上儿童一次 10 ml, 一日 2 次。",
        "side_effects": "偶见胃部不适、恶心、呕吐。",
        "contraindications": "对本品过敏者禁用。",
        "source": "《咳嗽基层诊疗指南》",
    },
    {
        "drug_name": "氢溴酸右美沙芬糖浆",
        "category": "镇咳",
        "indications": "用于干咳, 包括上呼吸道感染 (感冒、咽炎)、支气管炎等引起的干咳。",
        "dosage": "口服。成人一次 10-20 ml, 一日 3-4 次。",
        "side_effects": "偶见头晕、嗜睡、便秘。",
        "contraindications": "痰多咳嗽者不宜使用。驾驶机/车/船者慎用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "复方甘草片",
        "category": "镇咳 / 复方",
        "indications": "用于镇咳祛痰。",
        "dosage": "口服或含化。成人一次 3-4 片, 一日 3 次。",
        "side_effects": "长期使用可致成瘾性 (含阿片成分)。",
        "contraindications": "对本品成分过敏者禁用。妊娠头 3 个月禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "复方草珊瑚含片",
        "category": "咽喉 / 含片",
        "indications": "用于外感风热所致的喉痹, 症见咽喉肿痛、声哑失音; 急性咽喉炎见上述证候者。",
        "dosage": "含服。一次 1-2 片, 每小时 2-4 片, 一日 6-12 片。",
        "side_effects": "偶见恶心、口干。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "西瓜霜润喉片",
        "category": "咽喉 / 含片",
        "indications": "用于咽喉肿痛、声音嘶哑、口舌生疮。",
        "dosage": "含服。一次 1-2 片, 一日数次。",
        "side_effects": "偶见口干。",
        "contraindications": "孕妇慎用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "盐酸羟甲唑啉鼻喷",
        "category": "鼻喷 / 减充血",
        "indications": "用于急慢性鼻炎、鼻窦炎、过敏性鼻炎引起的鼻塞。",
        "dosage": "喷鼻。成人和 6 岁以上儿童, 一次每侧鼻孔 1-2 喷, 一日 2 次, 连续使用不超过 7 天。",
        "side_effects": "偶见鼻腔干燥、烧灼感。长期使用可致药物性鼻炎。",
        "contraindications": "萎缩性鼻炎及鼻腔干燥者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "糠酸莫米松鼻喷雾剂",
        "category": "鼻用糖皮质激素",
        "indications": "用于治疗成人、青少年和 3-11 岁儿童的季节性或常年性过敏性鼻炎。",
        "dosage": "喷鼻。成人及 12 岁以上儿童: 每侧鼻孔 2 喷, 一日 1 次。",
        "side_effects": "偶见鼻腔干燥、鼻出血、咽炎。",
        "contraindications": "鼻部感染未控制者禁用。",
        "source": "《变应性鼻炎诊断和治疗指南》2022",
    },
    {
        "drug_name": "硝苯地平控释片",
        "category": "降压 / CCB (需处方)",
        "indications": "用于原发性高血压、慢性稳定型心绞痛。",
        "dosage": "口服, 整片吞服, 不可掰开或咀嚼。常用剂量一次 30 mg, 一日 1 次。",
        "side_effects": "面红、头痛、踝部水肿、心悸、便秘。",
        "contraindications": "心源性休克、严重主动脉瓣狭窄、孕妇禁用。",
        "source": "《中国高血压防治指南》2024",
    },
    {
        "drug_name": "缬沙坦胶囊",
        "category": "降压 / ARB (需处方)",
        "indications": "用于轻、中度原发性高血压。",
        "dosage": "口服。一次 80 mg, 一日 1 次, 血压控制不理想时可增至 160 mg 或与其他降压药联用。",
        "side_effects": "偶见头晕、咳嗽少见 (与 ACEI 不同)。",
        "contraindications": "对本品过敏者禁用。妊娠期妇女禁用。",
        "source": "《中国高血压防治指南》2024",
    },
    {
        "drug_name": "盐酸二甲双胍片",
        "category": "降糖 (需处方)",
        "indications": "首选用于单纯饮食控制及体育锻炼治疗无效的 2 型糖尿病, 特别是肥胖的 2 型糖尿病。",
        "dosage": "口服, 餐时或餐后即刻服用, 减少胃肠道反应。起始一次 0.5 g, 一日 2-3 次, 一日最大剂量 2 g。",
        "side_effects": "恶心、呕吐、腹泻、口中有金属味。罕见乳酸性酸中毒。",
        "contraindications": "严重肾功能不全 (eGFR < 45)、酮症酸中毒、严重感染、脱水患者禁用。",
        "source": "《中国 2 型糖尿病防治指南》2024",
    },
    {
        "drug_name": "阿托伐他汀钙片",
        "category": "调脂 (需处方)",
        "indications": "用于高胆固醇血症、混合型高脂血症及冠心病和脑卒中的防治。",
        "dosage": "口服, 任意时间服用, 不受进餐影响。常用起始剂量一次 10 mg, 一日 1 次, 可根据需要调整至 80 mg。",
        "side_effects": "肌痛、肌酸激酶升高、转氨酶升高。",
        "contraindications": "活动性肝病、严重肝功能不全、孕妇及哺乳期妇女禁用。",
        "source": "《中国血脂管理指南》2023",
    },
    {
        "drug_name": "复方甘草酸苷片",
        "category": "保肝 (需处方)",
        "indications": "用于治疗慢性肝病, 改善肝功能异常; 也可用于治疗湿疹、皮肤炎、斑秃。",
        "dosage": "口服。成人一次 2-3 片, 一日 3 次, 餐后服用。",
        "side_effects": "罕见假性醛固酮增多症。",
        "contraindications": "醛固酮症、低钾血症、肌营养不良患者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "蒙脱石散",
        "category": "止泻",
        "indications": "用于成人及儿童急、慢性腹泻。",
        "dosage": "温水冲服, 食管炎患者饭后服用, 其他患者两餐之间空腹服用。成人一次 1 袋 (3g), 一日 3 次。1 岁以下一日 1 袋, 1-2 岁一日 1-2 袋, 2 岁以上一日 2-3 袋。",
        "side_effects": "偶见便秘。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "口服补液盐 III",
        "category": "补液 / 止泻辅助",
        "indications": "用于治疗和预防急、慢性腹泻造成的轻中度脱水。",
        "dosage": "临用前将 1 袋 (5.125 g) 溶于 250 ml 温开水中, 随时口服。儿童开始时 50 ml/kg, 4 小时内服完, 之后根据脱水程度调整。",
        "side_effects": "偶见恶心、呕吐。",
        "contraindications": "严重脱水伴休克、少尿或无尿者禁用。",
        "source": "WHO 推荐",
    },
    {
        "drug_name": "双歧杆菌四联活菌片",
        "category": "益生菌",
        "indications": "用于治疗与肠道菌群失调相关的腹泻、便秘、功能性消化不良。",
        "dosage": "口服, 餐后用温水 (≤40°C) 送服。成人一次 3 片, 一日 3 次。",
        "side_effects": "偶见腹胀。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "云南白药气雾剂",
        "category": "外用 / 跌打",
        "indications": "用于跌打损伤、扭挫伤、肌肉酸痛、关节疼痛。",
        "dosage": "外用。喷于患处, 一日 3-5 次。",
        "side_effects": "偶见皮肤过敏。",
        "contraindications": "皮肤破损处禁用。孕妇禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "红霉素眼膏",
        "category": "眼科外用",
        "indications": "用于沙眼、结膜炎、睑缘炎及眼外部感染。",
        "dosage": "涂于眼睑内, 一日 2-3 次, 睡前最后一次。",
        "side_effects": "偶见局部刺激。",
        "contraindications": "对大环内酯类抗生素过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "开瑞坦 (氯雷他定糖浆)",
        "category": "儿童抗过敏",
        "indications": "用于缓解过敏性鼻炎症状 (喷嚏、流涕、鼻痒) 及慢性荨麻疹。",
        "dosage": "口服。2-12 岁儿童: 体重 > 30 kg, 一次 10 ml, 一日 1 次; 体重 ≤ 30 kg, 一次 5 ml, 一日 1 次。",
        "side_effects": "偶见嗜睡、头痛。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "褪黑素片",
        "category": "助眠 / 保健",
        "indications": "用于改善睡眠质量, 适用于入睡困难、多梦、易醒等。",
        "dosage": "口服, 睡前 30 分钟服用。成人一次 1-3 mg, 一日 1 次。",
        "side_effects": "偶见嗜睡、头痛。",
        "contraindications": "孕妇、哺乳期妇女、儿童、自身免疫性疾病患者禁用。",
        "source": "《中国成人失眠诊断和治疗指南》",
    },
    {
        "drug_name": "健胃消食片",
        "category": "中成药 / 助消化",
        "indications": "用于脾胃虚弱所致的食积, 症见不思饮食、嗳腐酸臭、脘腹胀满; 消化不良见上述证候者。",
        "dosage": "口服或咀嚼。一次 3 片, 一日 3 次。",
        "side_effects": "偶见口干。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "多潘立酮片 (吗丁啉)",
        "category": "促胃肠动力",
        "indications": "用于消化不良、腹胀、嗳气、恶心、呕吐。",
        "dosage": "口服, 饭前 15-30 分钟服用。成人一次 10 mg, 一日 3 次。",
        "side_effects": "偶见口干、头痛、腹泻。罕见 QT 间期延长。",
        "contraindications": "已知 QT 间期延长、心律失常、正在使用酮康唑等 CYP3A4 强抑制剂者禁用。中重度肝功能不全者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "开塞露",
        "category": "通便 / 外用",
        "indications": "用于便秘, 尤其适用于老年体弱及小儿便秘。",
        "dosage": "肛门注入。一次 1 支 (20 ml), 用时剪开管口, 缓慢插入肛门, 挤入药液。",
        "side_effects": "偶见肛门局部刺激。",
        "contraindications": "对本品过敏者禁用。肠道穿孔、肠梗阻患者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "碘伏溶液",
        "category": "外用 / 消毒",
        "indications": "用于皮肤消毒, 小伤口、擦伤、烫伤的局部消毒。",
        "dosage": "外用, 直接涂于患处或用棉球蘸取后涂抹, 一日 1-2 次。",
        "side_effects": "偶见皮肤刺激。",
        "contraindications": "对碘过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "医用酒精 (75% 乙醇)",
        "category": "外用 / 消毒",
        "indications": "用于皮肤消毒。",
        "dosage": "外用, 用棉球蘸取后擦拭患处。",
        "side_effects": "偶见皮肤干燥。",
        "contraindications": "对乙醇过敏者禁用。黏膜及破损皮肤慎用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "创可贴 (苯扎氯铵贴)",
        "category": "外用 / 止血",
        "indications": "用于小创伤、擦伤等患处的止血、护创。",
        "dosage": "撕开包装, 贴于清洁后的伤口, 每天更换 1-2 次。",
        "side_effects": "偶见皮肤过敏。",
        "contraindications": "对苯扎氯铵过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "扶他林 (双氯芬酸二乙胺乳胶剂)",
        "category": "外用 / 镇痛",
        "indications": "用于缓解肌肉、软组织和关节的轻至中度疼痛, 如腰背痛、扭伤、肩周炎、关节痛。",
        "dosage": "外用, 按痛处面积大小, 一次 2-4 g, 一日 3-4 次, 涂于患处并轻轻揉搓。",
        "side_effects": "偶见皮肤过敏、瘙痒。",
        "contraindications": "对双氯芬酸、阿司匹林或其他非甾体抗炎药过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "西瓜霜喷剂",
        "category": "咽喉 / 中成药外用",
        "indications": "用于咽喉肿痛、口舌生疮、口腔溃疡。",
        "dosage": "外用, 喷(吹)敷患处, 一次适量, 一日 3-4 次。",
        "side_effects": "偶见口干。",
        "contraindications": "孕妇慎用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "阿昔洛韦乳膏",
        "category": "外用 / 抗病毒",
        "indications": "用于单纯疱疹、带状疱疹、生殖器疱疹。",
        "dosage": "外用, 涂于患处, 一日 5-6 次, 疗程 7-10 天。",
        "side_effects": "偶见局部灼热、瘙痒、皮疹。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "炉甘石洗剂",
        "category": "外用 / 止痒",
        "indications": "用于皮肤瘙痒、湿疹、痱子、蚊虫叮咬。",
        "dosage": "外用, 用前摇匀, 涂于患处, 一日数次。",
        "side_effects": "极少, 偶见皮肤干燥。",
        "contraindications": "皮肤有破溃处禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "生理盐水 (氯化钠注射液 0.9%)",
        "category": "外用 / 清洗",
        "indications": "用于鼻腔冲洗、伤口清洗、隐形眼镜清洗。",
        "dosage": "外用, 视用途而定。鼻腔冲洗: 一次每侧鼻孔 100-200 ml, 一日 1-2 次。",
        "side_effects": "罕见过敏。",
        "contraindications": "无明显禁忌。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "复方鱼肝油滴剂",
        "category": "外用 / 鼻干",
        "indications": "用于干燥性鼻炎、萎缩性鼻炎。",
        "dosage": "滴鼻。一次每侧鼻孔 1-2 滴, 一日 2-3 次。",
        "side_effects": "偶见鼻部刺激。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "阿胶补血口服液",
        "category": "中成药 / 补血",
        "indications": "用于久病体弱、血亏目昏、虚劳咳嗽; 缺铁性贫血。",
        "dosage": "口服。一次 20 ml, 一日 2-3 次。",
        "side_effects": "偶见胃部不适。",
        "contraindications": "感冒发热病人不宜服用。糖尿病患者慎用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "钙尔奇D3片",
        "category": "补钙",
        "indications": "用于妊娠和哺乳期妇女、更年期妇女、老年人等的钙补充剂, 防治骨质疏松。",
        "dosage": "口服。一次 1 片, 一日 1-2 次, 餐后服用。",
        "side_effects": "偶见嗳气、便秘。",
        "contraindications": "高钙血症、高尿酸血症、肾结石患者禁用。",
        "source": "国家药品说明书",
    },
    {
        "drug_name": "盐酸氨基葡萄糖胶囊",
        "category": "关节 / 保健",
        "indications": "用于治疗和预防全身所有部位的骨关节炎, 包括膝关节、髋关节、脊柱、肩、手和腕关节等。",
        "dosage": "口服。一次 0.75 g, 一日 2 次, 进食时服用更好。",
        "side_effects": "偶见轻度胃部不适、恶心、便秘。",
        "contraindications": "对本品过敏者禁用。",
        "source": "国家药品说明书",
    },
]
