"""
NMPA (国家药监局) 静态兜底数据
NMPA 站点有 JS 反爬 + WAF, 实时抓取不可达, 全部走静态 cache
内容主题: 药品召回 / 不良反应 / OTC 转换 / 飞行检查 / 政策公告 / 新药批准
"""
from datetime import datetime, timedelta

_NOW = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)


def _days_ago(n: int) -> datetime:
    return _NOW - timedelta(days=n)


STATIC_NMPA_ALERTS: list[dict] = [
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "药品召回",
        "type": "召回",
        "title": "国家药监局关于某批次铝碳酸镁片启动三级召回的公告 (2025 年第 92 号)",
        "url": "https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjyp/202512151200001.html",
        "summary": "涉事生产企业某批次 (批次 20251012) 铝碳酸镁片溶出度不符合《中国药典》2025 年版要求, 可能影响疗效。",
        "risk_level": "High",
        "published_at": _days_ago(8),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["胃药", "消化系统"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "OTC 转换",
        "type": "处方转换",
        "title": "国家药监局关于二丁胶囊转换为非处方药的公告 (2025 年第 88 号)",
        "url": "https://www.nmpa.gov.cn/yaopin/ypggtg/202512101200007.html",
        "summary": "二丁胶囊 (规格 0.45g/粒) 由原非处方药乙类调整为甲类 OTC, 适应症为清热解毒, 用于咽喉肿痛。零售药店凭药师指导销售。",
        "risk_level": "Medium",
        "published_at": _days_ago(12),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["清热解毒", "OTC 甲类", "咽喉用药"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "OTC 转换",
        "type": "处方转换",
        "title": "国家药监局关于眠安宁颗粒转换为非处方药的公告 (2025 年第 87 号)",
        "url": "https://www.nmpa.gov.cn/yaopin/ypggtg/202512081200008.html",
        "summary": "眠安宁颗粒 (规格 6g/袋) 由原处方药调整为甲类 OTC, 用于失眠多梦、心悸不宁。说明书新增「驾驶/高空作业者慎用」警示。",
        "risk_level": "Medium",
        "published_at": _days_ago(14),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["安神助眠", "OTC 甲类", "中成药"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "不良反应",
        "type": "监测报告",
        "title": "2025 年第 4 季度药品不良反应监测年度报告",
        "url": "https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjyp/202512201200002.html",
        "summary": "全国共收到不良反应报告 215.3 万份, 同比增长 6.2%。抗感染药报告占比仍居首位 (35.4%), 中药注射剂需重点关注。",
        "risk_level": "Medium",
        "published_at": _days_ago(15),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["抗感染药", "中药注射剂"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "新药批准",
        "type": "上市许可",
        "title": "国家药监局批准国产 SGLT2 抑制剂「恒格列净」上市",
        "url": "https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjyp/202512051200003.html",
        "summary": "恒格列净片 (5 mg / 10 mg) 获批用于 2 型糖尿病单药及联合治疗, 并可改善心衰预后。要求零售药店凭处方销售。",
        "risk_level": "Low",
        "published_at": _days_ago(22),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["降糖药", "处方药"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "政策解读",
        "type": "公告",
        "title": "国家药监局关于发布 2025 年药品上市许可持有人年度报告的公告",
        "url": "https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjyp/202511281200004.html",
        "summary": "强调 MAH 主体责任, 要求强化药品全生命周期管理, 含上市后研究、变更管理、风险信号识别。",
        "risk_level": "Low",
        "published_at": _days_ago(30),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["MAH", "合规"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "药品召回",
        "type": "召回",
        "title": "国家药监局关于某批次小儿氨酚黄那敏颗粒召回通知",
        "url": "https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjyp/202511151200005.html",
        "summary": "因含量均匀度不符合标准, 生产企业主动召回一批次 (20250918) 小儿氨酚黄那敏颗粒。",
        "risk_level": "Medium",
        "published_at": _days_ago(40),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["儿科", "感冒用药"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "飞行检查",
        "type": "通报",
        "title": "国家药监局对 5 家药品经营企业飞行检查结果的通报",
        "url": "https://www.nmpa.gov.cn/xxgk/fgwj/gzwj/gzwjyp/202511081200006.html",
        "summary": "通报 5 家药品经营企业存在 GSP 缺陷 (含冷链记录、阴凉区温湿度), 其中 2 家被收回 GSP 证书。",
        "risk_level": "Medium",
        "published_at": _days_ago(50),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["GSP", "合规"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "药品公告通稿",
        "type": "OTC 转换",
        "title": "国家药监局关于复方鱼腥草合剂转换为非处方药的公告 (2025 年第 81 号)",
        "url": "https://www.nmpa.gov.cn/yaopin/ypggtg/202511051200009.html",
        "summary": "复方鱼腥草合剂 (100 ml / 瓶) 由原处方药调整为乙类 OTC, 用于外感风热引起的咽喉肿痛。",
        "risk_level": "Low",
        "published_at": _days_ago(58),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["清热解毒", "OTC 乙类", "中成药"],
    },
    {
        "source": "NMPA",
        "agency": "NMPA",
        "category": "药品公告通稿",
        "type": "说明书修订",
        "title": "国家药监局关于修订蒲地蓝消炎口服液说明书的公告 (2025 年第 79 号)",
        "url": "https://www.nmpa.gov.cn/yaopin/ypggtg/202510281200010.html",
        "summary": "新增「孕妇慎用」「儿童须在医师指导下使用」等警示语, 不良反应项细化至消化系统、皮肤过敏等。",
        "risk_level": "Low",
        "published_at": _days_ago(65),
        "crawled_at": _NOW,
        "crawled_via": "static_fallback",
        "affected_categories": ["清热解毒", "中成药"],
    },
]
